# Generated by Django 4.1.1 on 2023-06-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderPayment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='custid',
            new_name='userid',
        ),
    ]
