# Generated by Django 4.1.1 on 2023-06-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='food_images')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
